### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by olirob93** [adampaulsackfield/todo-app#10]
| Category          | Score |
| ----------------- | ----- |
| Brief stages      | 50/ 50  |
| Project Structure | 20/ 20  |
| Code Quality      | 20/ 30  |
| Source Control    | 10/ 10  |
| Total Score       | 110/ 110 |

## Feedback

This project is top-class!! 

I love that you keep pushing rather than just cruising through hitting off the MVP of the projects, keep this going as it will stand you in very good stead when you land your role. There isn't much I can find at fault with this other than some small admin bits so really well done Adam.

### Positive

- Love that you have written this in typescript, keep pushing the boundaries!
- It's really nice you have added an ENV file to hide your passwords and other valuable data
- The custom errors functions and testing are just icing on the cake
- Love that you added new branches for features and didn't just do it all in the main branch

### Constructive

- Not much here but would have been handy to add some dummy data in a JSON for when we come to test / review the code.
- Your `READ_ME.md` is great but it can be taken to the next level with screenshots and also adding issues you ran into and how you overcame them. Even if they seem small to you when an employer is looking at this they can see you understood the problem and came up with a resolution.

**Comment by adampaulsackfield** [comment]
@olirob93 Thanks for the amazing feedback. I feel I set a high standard for myself at the start and I need to maintain that now.

I will implement the changes under constructive, just in case others ever come and look at it
